<?php 
/**
 * Template for index action
 * 
 * @category   OntoWiki
 * @package    OntoWiki_extensions_patapro
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>

<div class="firstHeadline"><?php echo $this->_translate->_('patient proposal allocation'); ?></div>
<div class="secondHeadline"><?php echo $this->_translate->_('allocate proposals to a patient'); ?></div>
<?php if ("" != $this->currentPatient) { ?>
    <form method="post" action="" id="patapro">
        <table id="main">
            <tr>
                <th>
                    <div>
                        <span><?php echo $this->_translate->_('healthstate'); ?></span>
                        <select name="selectHealthstate" id="selectHealthstate" onchange="getHealthstate('selectHealthstate');">
                            <?php foreach ($this->healthstates as $healthstateUri => $healthstateTS) { ?>
                                <option value="<?php echo $healthstateUri?>"><?php echo $healthstateTS ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </th>
                <th><div><?php echo $this->_translate->_('proposals'); ?></div></th>
            </tr>
            <tr>
                <td id="healthstateCol">
                    <div id="healthstate">
                        <?php echo $this->render('patapro/healthstate.phtml'); ?>
                    </div>
                </td>
                <td id="proposalCol">
                    <table id="proposal">
                        <tr>
                            <th></th>
                            <th><?php echo $this->_translate->_('proposal'); ?></th>
                            <th><?php echo $this->_translate->_('status'); ?></th>
                            <th><?php echo $this->_translate->_('correspondence'); ?></th>
                        </tr>
                        <?php foreach ($this->proposals as $proposalUri => $proposal) { ?> 
                             <tr>
                                <td id="proposalCheck">
                                    <input type="checkbox"
                                        <?php echo (isset($proposal['status']) && "isPending" != $proposal['status'] ? "disabled=\"disabled\"" : ""); ?>
                                        name="proposals[]" value="<?php echo urlencode($proposalUri); ?>"
                                        <?php echo (isset($proposal['status']) ? "checked=\"checked\"" : ""); ?>
                                    >
                                </td>
                                <td id="proposalName">
                                    <span<?php echo (0 < $proposal['correspondence'] ? ' style="font-weight:bold"' : ''); ?>><?php echo $proposal['label']; ?></span>
                                </td>
                                <td id="proposalStatus">
                                    <span><?php echo (isset($proposal['status']) ? $this->_translate->_($proposal['status']) : ""); ?></span>
                                </td>
                                <td id="proposalCorrespondence">
                                    <div class="correspondence corDivBottom"></div><div style="width:<?php echo $proposal['correspondence']; ?>px" class="correspondence corDivTop"></div>
                                </td>
                            </tr>
                        <?php } ?>
                    </table>
                </td>
            </tr>
        </table>
        
        <input type="hidden" name="do" value="save"/>
        <div id="formButtons">
            <a id="addResource" class="button submit" onclick="document.forms['patapro'].submit();"/>
            <?php echo $this->_translate->_('save'); ?></a>
        </div>
    </form>
<?php } ?>