<?php 
/**
 * Template for index action
 * 
 * @category   OntoWiki
 * @package    OntoWiki_extensions_patapro
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>
<script type="text/javascript">
    var url = '<?php echo $this->url; ?>';
    var healthstates = '<?php echo (isset($this->healthstates) ? json_encode($this->healthstates) : "") ?>';
    var statusArray = $.parseJSON('<?php echo json_encode($this->statusArray) ?>');
    var sortArray = $.parseJSON('<?php echo json_encode($this->sortArray) ?>');
    var messages = new Array();
</script>
<!-- set the title of the action -->
<?php $this->placeholder('main.window.title')->set($this->_translate->_('patient proposal allocation')); ?>
<div id="box"></div>
<div class="headline">
    <div class="firstHeadline"><?php echo $this->_translate->_('patient proposal allocation'); ?></div>
    <div class="secondHeadline"><?php echo $this->_translate->_('allocate proposals to a patient'); ?></div>
</div>
<div id="messageBox"></div>
<div class="clear"></div>
<?php if ("" != $this->currentPatient && 0 < count($this->healthstates)) { reset($this->healthstates); ?>
    <form method="post" action="" id="patapro">
        <table id="main">
            <tr>
                <th>
                    <div>
                        <span id="spanHealthStateTypeLabel"><?php echo (0 < count($this->healthstates) ? $this->healthstates[key($this->healthstates)]['typeLabel'] : '') ?></span>
                        <select name="selectHealthstate" id="selectHealthstate" onchange="getHealthstate('selectHealthstate');">
                            <?php foreach ($this->healthstates as $healthstateUri => $healthstate) { ?>
                                <option value="<?php echo $healthstateUri?>"><?php echo $healthstate['timestamp'] ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </th>
                <th><div><?php echo $this->_translate->_('proposals'); ?></div></th>
            </tr>
            <tr>
                <td id="healthstateCol">
                    <div id="healthstate">
                        <?php echo $this->render('patapro/healthstate.phtml'); ?>
                    </div>
                </td>
                <td id="proposalCol">
                    <table id="proposal">
                        <tr>
                            <th></th>
                            <th><?php echo $this->_translate->_('proposal'); ?></th>
                            <th><?php echo $this->_translate->_('status'); ?></th>
                            <th><?php echo $this->_translate->_('correspondence'); ?></th>
                        </tr>
                        <tr><td class="trPatientProposal" id="trAllocated" colspan="4"><?php echo $this->_translate->_('allocated'); ?> <?php echo $this->_translate->_('proposals'); ?></td></tr>
                        <?php foreach ($this->patientProposals as $proposalUri => $proposal) { ?>
                            <tr class="trPatientProposal" id="<?php echo md5($proposalUri) ?>" >
                                <td id="proposalCheck">
                                    <input id="input<?php echo md5($proposalUri); ?>" type="checkbox"
                                        <?php echo (isset($proposal['status']) && "isPending" != $proposal['status'] ? "disabled=\"disabled\"" : ""); ?>
                                        name="proposals[]" value="<?php echo urlencode($proposalUri); ?>"
                                        onchange="javascript:loadProposalBoxCheck('<?php echo urlencode($proposalUri) ?>', '<?php echo urlencode($this->patientUri) ?>','<?php echo md5($proposalUri) ?>')"
                                        <?php echo (isset($proposal['status']) ? "checked=\"checked\"" : ""); ?>
                                    >
                                </td>
                                <td id="proposalName">
                                    <span<?php echo (isset ($proposal['correspondence']) && 0 < $proposal['correspondence'] ? ' style="font-weight:bold"' : ''); ?>><?php echo $proposal['label']; ?></span>
                                    <a href="javascript:loadProposalBox('<?php echo urlencode($proposalUri) ?>', '<?php echo urlencode($this->patientUri) ?>','<?php echo md5($proposalUri) ?>')">
                                        <img src="<?php echo $this->url; ?>../extensions/themes/dispedia/images/icon-edit.png">
                                    </a>
                                </td>
                                <td id="proposalStatus">
                                    <span data-status="<?php echo (isset($proposal['status']) ? $proposal['status'] : "new") ?>"><?php echo (isset($proposal['status']) ? $proposal['statusLabel'] : ""); ?></span>
                                </td>
                                <td id="proposalCorrespondence">
                                    <div class="correspondence corDivBottom"></div>
                                    <div class="correspondence corDivTop" data-correspondence="<?php echo (isset ($proposal['correspondence']) ? $proposal['correspondence'] : 0); ?>" style="width:<?php echo (isset ($proposal['correspondence']) ? $proposal['correspondence'] : 0); ?>px"></div>
                                </td>
                            </tr>
                        <?php } ?>
                        <tr id="seperator"><td colspan="4"></td></tr>
                        <tr class="secondHeadline"><td colspan="4"><?php echo $this->_translate->_('notAllocated'); ?> <?php echo $this->_translate->_('proposals'); ?></td></tr>
                        <?php foreach ($this->proposals as $proposalUri => $proposal) { ?>
                            <tr id="<?php echo md5($proposalUri) ?>">
                                <td id="proposalCheck">
                                    <input id="input<?php echo md5($proposalUri); ?>" type="checkbox"
                                        <?php echo (isset($proposal['status']) && "isPending" != $proposal['status'] ? "disabled=\"disabled\"" : ""); ?>
                                        name="proposals[]" value="<?php echo urlencode($proposalUri); ?>"
                                        onchange="javascript:loadProposalBoxCheck('<?php echo urlencode($proposalUri) ?>', '<?php echo urlencode($this->patientUri) ?>','<?php echo md5($proposalUri) ?>')"
                                        <?php echo (isset($proposal['status']) ? "checked=\"checked\"" : ""); ?>
                                    >
                                </td>
                                <td id="proposalName">
                                    <span<?php echo (isset ($proposal['correspondence']) && 0 < $proposal['correspondence'] ? ' style="font-weight:bold"' : ''); ?>><?php echo $proposal['label']; ?></span>
                                    <a href="javascript:loadProposalBox('<?php echo urlencode($proposalUri) ?>', '<?php echo urlencode($this->patientUri) ?>','<?php echo md5($proposalUri) ?>')">
                                        <img src="<?php echo $this->url; ?>../extensions/themes/dispedia/images/icon-edit.png">
                                    </a>
                                </td>
                                <td id="proposalStatus">
                                    <span data-status="<?php echo (isset($proposal['status']) ? $proposal['status'] : "new") ?>"><?php echo (isset($proposal['status']) ? $proposal['statusLabel'] : ""); ?></span>
                                </td>
                                <td id="proposalCorrespondence">
                                    <div class="correspondence corDivBottom"></div>
                                    <div class="correspondence corDivTop" data-correspondence="<?php echo (isset ($proposal['correspondence']) ? $proposal['correspondence'] : 0); ?>" style="width:<?php echo (isset ($proposal['correspondence']) ? $proposal['correspondence'] : 0); ?>px"></div>
                                </td>
                            </tr>
                        <?php } ?>
                    </table>
                </td>
            </tr>
        </table>
    </form>
<?php } ?>