<?php 
/**
 * Template for index action
 * 
 * @category   OntoWiki
 * @package    OntoWiki_extensions_patapro
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>
<form method="post" action="" id="patapro">
    <table>
        <tr>
            <td width="20%">
                <br /><br />
                <?php foreach ($this->patients as $patient) { ?>
                    
                <div><a href="<?php echo $this->url . '?patientUri=' . $patient['uri']; ?>"><?php echo $patient['firstName'] . ' ' . $patient['lastName']; ?></a></div><br />
                
                <?php } ?>
            </td>
            <td width="40%">
                <br /><br />
                <?php foreach ($this->options as $topicLabel => $topic) { ?>
                    <div><h2><?php echo $topicLabel; ?></h2></div><br />
                    <?php foreach ($topic as $option) { ?>
                        
                    <div><?php echo $option['optionLabel']; ?></div><br />
                    
                    <?php } ?>
                <?php } ?>
            </td>
            <td width="40%">
                <br /><br />
                <?php if ("" != $this->currentPatient)
                      foreach ($this->proposals as $proposalUri => $proposal) { ?>
                    
                    <div><input type="checkbox" name="<?php echo $proposalUri; ?>" value="selectedOption" <?php echo (isset($proposal['checked']) ? "checked=\"checked\"" : ""); ?>>&nbsp&nbsp<?php echo $proposal['label']; ?></div><br />
                
                <?php } ?>
            </td>
        </tr>
    </table>
    
    <input type="hidden" name="do" value="save"/>
    
    <a id="addResource" class="button submit" onclick="document.forms['patapro'].submit();"/>
        <?php echo $this->_translate->_('Save'); ?></a>
</form>
