<?php 
/**
 * Template for index action
 * 
 * @category   OntoWiki
 * @package    OntoWiki_extensions_patapro
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>

<!-- set the title of the action -->
<?php $this->placeholder('main.window.title')->set($this->_translate->_('decisions')); ?>

<div class="firstHeadline"><?php echo $this->_translate->_('decisions'); ?></div>
<div class="secondHeadline"><?php echo $this->_translate->_('make your decisions'); ?></div>
<?php if ("" != $this->currentPatient) { ?>
    <form method="POST" action="" id="patapro">
        <table>
            <tr>
                <td id="decisionCol">
                    <div class="sectionHeadline"><?php echo $this->_translate->_('new'); ?> <?php echo $this->_translate->_('proposals'); ?></div>
                    <div class="section">
                        <?php foreach ($this->decisionProposals as $proposal) { ?>
                        <?php if ("isPending" == $proposal['status']) { ?>
                            <div>
                                <div class="proposal"><?php echo $proposal['label'] ?></div>
                                <div class="decision"><input type="radio" name="<?php echo base64_encode($proposal['decision']) ?>" value="accepts"><span><?php echo $this->_translate->_('accept'); ?></span></div>
                                <div class="decision"><input type="radio" name="<?php echo base64_encode($proposal['decision']) ?>" value="denies"><span><?php echo $this->_translate->_('denies'); ?></span></div>
                                <div class="decision"><input type="radio" name="<?php echo base64_encode($proposal['decision']) ?>" value="isPending"><span><?php echo $this->_translate->_('pending'); ?></span></div>
                                <div class="clear"></div>
                            </div>
                        <?php } ?>
                        <?php } ?>
                    </div>
                    <div class="sectionHeadline"><?php echo $this->_translate->_('accepts'); ?> <?php echo $this->_translate->_('proposals'); ?></div>
                    <div class="section">
                        <?php foreach ($this->decisionProposals as $proposal) { ?>
                            <?php if ("accepts" == $proposal['status']) { ?>
                                <div>
                                    <div class="proposal"><?php echo $proposal['proposalLabel'] ?></div>
                                    <div class="decision"><input type="radio" name="<?php echo base64_encode($proposal['decision']) ?>" value="denies"><span><?php echo $this->_translate->_('denies'); ?></span></div>
                                    <div class="decision"><input type="radio" name="<?php echo base64_encode($proposal['decision']) ?>" value="isPending"><span><?php echo $this->_translate->_('pending'); ?></span></div>
                                <div class="clear"></div>
                                </div>
                            <?php } ?>
                        <?php } ?>
                    </div>
                    <div class="sectionHeadline"><?php echo $this->_translate->_('denieds'); ?> <?php echo $this->_translate->_('proposals'); ?></div>
                    <div class="section">
                        <?php foreach ($this->decisionProposals as $proposal) { ?>
                        <?php if ("denies" == $proposal['status']) { ?>
                            <div>
                                <div class="proposal"><?php echo $proposal['proposalLabel'] ?></div>
                                <div class="decision"><input type="radio" name="<?php echo base64_encode($proposal['decision']) ?>" value="accepts"><span><?php echo $this->_translate->_('accept'); ?></span></div>
                                <div class="decision"><input type="radio" name="<?php echo base64_encode($proposal['decision']) ?>" value="isPending"><span><?php echo $this->_translate->_('pending'); ?></span></div>
                                <div class="clear"></div>
                            </div>
                        <?php } ?>
                        <?php } ?>
                    </div>
                </td>
            </tr>
        </table>
        <input type="hidden" name="do" value="save"/>
    </form>
<?php } ?>

