<?php 
/**
 * Template for index action
 * 
 * @category   OntoWiki
 * @package    OntoWiki_extensions_patapro
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>
<form method="POST" action="" id="patapro">
    <table>
	<tr>
	    <th><div>Patients</div></th>
	    <?php if ("" != $this->currentPatient) { ?>
		<th><div>Decisions</div></th>
	    <?php } ?>
	</tr>
	<tr> 
	    <td id="patientCol">
		<?php foreach ($this->patients as $patient) { ?>
		    <?php
			$patientCss = '';
			if ($patient ['uri'] == $this->currentPatient)
			    $patientCss = 'patientSelected';
		    ?>
		    <div class="patient <?php echo $patientCss; ?>">
			<a href="<?php echo $this->url . '?patientUri=' . $patient['uri']; ?>">
			    <?php echo $patient['firstName'] . ' ' . $patient['lastName']; ?>
			</a>
		    </div>
		<?php } ?>
	    </td>
	    <?php if (isset($this->currentPatient)) { ?>
		<td id="decisionCol">
		    <div class="sectionHeadline">Proposals</div>
		    <div class="section">
			<?php foreach ($this->decisionProposals as $proposal) { ?>
			<?php if ("http://als.dispedia.info/architecture/c/20110827/isPending" == $proposal['status']) { ?>
			    <div>
				<div class="proposal"><?php echo $proposal['proposalLabel'] ?></div>
				<div class="decision"><input type="radio" name="<?php echo base64_encode($proposal['decision']) ?>" value="accepts"> accept</div>
				<div class="decision"><input type="radio" name="<?php echo base64_encode($proposal['decision']) ?>" value="denies"> denies</div>
				<div class="decision"><input type="radio" name="<?php echo base64_encode($proposal['decision']) ?>" value="isPending"> undecided</div>
				<div class="clear"></div>
			    </div>
			<?php } ?>
			<?php } ?>
		    </div>
		    <div class="sectionHeadline">accepted Proposals</div>
		    <div class="section">
			<?php foreach ($this->decisionProposals as $proposal) { ?>
			    <?php if ("http://als.dispedia.info/architecture/c/20110827/accepts" == $proposal['status']) { ?>
				<div>
				    <div class="proposal"><?php echo $proposal['proposalLabel'] ?></div>
				    <div class="decision"><input type="radio" name="<?php echo base64_encode($proposal['decision']) ?>" value="denies"> denies</div>
				    <div class="decision"><input type="radio" name="<?php echo base64_encode($proposal['decision']) ?>" value="isPending"> undecided</div>
				<div class="clear"></div>
				</div>
			    <?php } ?>
			<?php } ?>
		    </div>
		    <div class="sectionHeadline">rejected Proposals</div>
		    <div class="section">
			<?php foreach ($this->decisionProposals as $proposal) { ?>
			<?php if ("http://als.dispedia.info/architecture/c/20110827/denies" == $proposal['status']) { ?>
			    <div>
				<div class="proposal"><?php echo $proposal['proposalLabel'] ?></div>
				<div class="decision"><input type="radio" name="<?php echo base64_encode($proposal['decision']) ?>" value="accepts"> accept</div>
				<div class="decision"><input type="radio" name="<?php echo base64_encode($proposal['decision']) ?>" value="isPending"> undecided</div>
				<div class="clear"></div>
			    </div>
			<?php } ?>
			<?php } ?>
		    </div>
		</td>
	    <?php } ?>
	</tr>
    </table>
    <input type="hidden" name="do" value="save"/>
    
    <?php if ("" != $this->currentPatient) { ?>
        <div id="formButtons"><a id="addResource" class="button submit" onclick="document.forms['patapro'].submit();"/></span>
            <?php echo $this->_translate->_('Save'); ?></a>
    <?php } ?>
</form>

