<?php 
/**
 * Template for index action
 * 
 * @category   OntoWiki
 * @package    OntoWiki_extensions_patapro
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>
<script type="text/javascript">       
    var url = '<?php echo $this->url; ?>';
    var models = <?php echo json_encode($this->models); ?>;
    var createUrl = url + "model/create";
    var addUrl = url + "model/add";
    var deleteUrl = url + "model/delete/";
</script>

<!-- set the title of the action -->
<?php $this->placeholder('main.window.title')->set($this->_translate->_('ontologieEdit')); ?>

<table>
	<tr>
		<td class="storeModelNameTd">
            <span class="storeModelNameSpan">All</span>
        </td>
        <td class="storeModelButtonTd">
            <a id="addResource" class="button" onclick="javascript:renewAllModel('all')">
                Renew 
            </a>
            <a id="addResource" class="button" onclick="javascript:renewAllModel('add')">
                Add
            </a>
            <a id="addResource" class="button" onclick="javascript:renewAllModel('delete')">
                Delete
            </a>
        </td>
        <td class="storeModelProcessTd">
            <div id="responseAll"></div>
        </td>
	</tr>
	<?php foreach($this->models as $modelName => $modelData) { ?>
        <tr>
            <?php if ('namespaces' != $modelName) { ?>
                <td class="storeModelNameTd">
                    <span class="storeModelNameSpan"><?php echo $modelName; ?></span>
                </td>
                <td class="storeModelButtonTd">
                    <a id="addResource" class="button" onclick="javascript:renewModel('<?php echo $modelName; ?>', 'all')">
                        Renew
                    </a>
                    <a id="addResource" class="button" onclick="javascript:renewModel('<?php echo $modelName; ?>', 'add')">
                        Add
                    </a>
                    <a id="addResource" class="button" onclick="javascript:renewModel('<?php echo $modelName; ?>', 'delete')">
                        Delete
                    </a>
                </td>
                <td class="storeModelProcessTd">
                    <div id="response<?php echo $modelName; ?>"></div>
                </td>
            <?php } ?>
        </tr>    
	<?php } ?>
    <tr><td><br /></td></tr>
    <tr>
        <td class="storeModelNameTd">
            Backup old ontologies?
        </td>
        <td class="storeModelButtonTd">
            <input id="storeBackup" class="checkbox" type="checkbox" name="backup" value="true" checked="checked">
        </td>
        <td>
        </td>
    </tr>
</table>


