<?php
$header = '
    <div id="header">
      <div class="wrapper">
	<img src="'. $this->baseUri .'/img/dispedia_logo.png" alt="Dispedia logo"/>
        <span class="lang">
	  <a href="' . $this->resourceUri . '?lang=en"><img src="'. $this->baseUri .'/img/en.png" title="english"/></a>
          <a href="' . $this->resourceUri . '?lang=de"><img src="'. $this->baseUri .'/img/de.png" title="deutsch"/></a>
        </span>
      </div>
    </div>';
echo $header;
?>
