<?php
    $navOptions = array(
            'navResource' => $this->wikiBaseUrl . 'Site/Navigation/Schemata',
            'navId' => 'nav-schemata',
            'suffix'    => '<!-- /#nav-schemata -->',
            'activeUrl' => $this->resourceUri,
            'listClass' => 'nav',
            'navClass' => 'nav-collapse'
            );
    echo $this->navigationList($navOptions);
?>
<div class="content">
    <?php
        // uses headline property for headline
        echo $this->literal(array('property' => 'http://ns.ontowiki.net/SysOnt/Site/headline', 'tag' => 'h1'));
        
        echo $this->img(array('property' => 'http://ns.ontowiki.net/SysOnt/Site/image', 'class' => 'aboutimg', 'alt' => 'infologistic'));
        // uses languageContent property for main content
        echo $this->literal(array('property' => 'http://ns.ontowiki.net/SysOnt/Site/languageContent', 'tag' => 'p', 'class' => 'about'));
    ?>
</div>