<div class="content schemaContent">
    <div class="dispediaSchema">
        <?php
            $fileName = $this->literal(
                array(
                    'property' => 'http://ns.ontowiki.net/SysOnt/Site/file',
                    'plain' => true
                )
            );
            echo $this->renderx(
                array(
                    'template' => 'dispedia/types/schemata/' . $fileName
                )
            );
        ?>
    </div>
</div>