<div class="content">
    <?php
        // uses headline property for headline
        echo $this->literal(array('property' => 'http://ns.ontowiki.net/SysOnt/Site/headline', 'tag' => 'h1'));
        
        echo $this->img(array('property' => 'http://ns.ontowiki.net/SysOnt/Site/image', 'class' => 'aboutimg', 'alt' => 'infologistic'));
        // uses languageContent property for main content
        echo $this->literal(array('property' => 'http://ns.ontowiki.net/SysOnt/Site/languageContent', 'tag' => 'p', 'class' => 'about'));
    ?>
    <br />
    <!-- Schema Navigation -->
    <?php
    echo $this->literal(array('property' => 'http://ns.ontowiki.net/SysOnt/Site/documentation', 'tag' => 'h2'));
    $navOptions = array(
            'navResource' => $this->wikiBaseUrl . 'Site/Navigation/Schemata',
            'navId' => 'schemas',
            'suffix'    => '<!-- /#nav-schemata -->',
            'activeUrl' => $this->resourceUri,
            'listClass' => 'nav',
            'navClass' => 'nav-collapse'
            );
    echo $this->navigationList($navOptions);
    ?>
    <!-- Schema Downloads -->
    <?php
    echo $this->literal(array('property' => 'http://ns.ontowiki.net/SysOnt/Site/downloadHeadline', 'tag' => 'h2'));
    ?>
    <div id="downloads">
        <?php
        // prepare downloads row
        $queryForDownloads = '
        PREFIX foaf: <http://xmlns.com/foaf/0.1/>
        SELECT DISTINCT ?resourceUri ?label
        WHERE {
            ?resourceUri ?propertyUri <http://ns.ontowiki.net/SysOnt/Site/Schema> .
            ?resourceUri <http://ns.ontowiki.net/SysOnt/Site/downloadLabel> ?label .
        }';
        $downloads = $this->querylist($queryForDownloads, 'dispedia/items/downloads.phtml');
        echo $downloads
        ?>
    </div>
</div>