<?php $this->placeholder('main.window.title')->set($this->_translate->_('DispediaHeadline')); ?>
<div style="padding:1em;">
<img style="float:left; width: 8em; margin:1em;" src="/htdocs/dispedia/img/dispedia_logo.png" />

<h1>
    Dispedia - <span style="font-style:italic;">Demonstration</span>
</h1>
<p style="text-indent:1em; text-align:justify;">
    <?php echo $this->_translate->_('text1') ?>
    <br /><br />
    <?php echo $this->_translate->_('text2') ?>
</p>
<p style="border: 1px dashed grey; background-color: #efefef; margin:1em; padding:1em ">
    <?php echo $this->_translate->_('user') ?>: guest <br>
    <?php echo $this->_translate->_('password') ?>: guest123
</p>
