<div class="content">
    <br /><br />
    <?php
        // uses headline property for headline
        echo $this->literal(array('property' => 'http://ns.ontowiki.net/SysOnt/Site/headline', 'tag' => 'h1'));
        
        // uses languageContent property for main content
        echo $this->literal(array('property' => 'http://ns.ontowiki.net/SysOnt/Site/languageContent', 'tag' => 'p', 'class' => 'contactContent'));
        
        // uses languageContent property for main content
        echo $this->img(array('property' => 'http://ns.ontowiki.net/SysOnt/Site/image', 'class' => 'contactImage'));
    ?>
</div>
<div class="clear"></div>
<div class="contentSeparator"></div>