<div class="content">
    <br /><br />
    <?php
        // uses headline property for headline
        echo $this->literal(array('property' => 'http://ns.ontowiki.net/SysOnt/Site/headline', 'tag' => 'h1'));
        
        // uses languageContent property for main content
        echo $this->literal(array('property' => 'http://ns.ontowiki.net/SysOnt/Site/languageContent', 'tag' => 'p', 'class' => 'about'));
        
        // uses content property for main content
        echo $this->literal(array('tag' => 'p', 'class' => 'about'));
    ?>
</div>
<div class="contentSeparator"></div>