<div class="content">
    <?php
        // uses headline property for headline
        echo $this->literal(array('property' => 'http://ns.ontowiki.net/SysOnt/Site/headline', 'tag' => 'h1'));
    ?>
    <div id="footerDivPartnerLogos">
        <table>
            <tbody>
                <tr>
                    <?php
                        // prepare main content (uses default content properties)
                        echo $this->literal(array('tag' => 'div', 'class' => 'partnerContent'));
                    ?>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="contentSeparator"></div>