<div style="padding:1em;">
<img style="float:left; width: 8em; margin:1em;" src="/htdocs/dispedia/page/dispedia_logo.png" />

<h1>
    Dispedia - <span style="font-style:italic;">Demonstration</span>
</h1>
<p style="text-indent:1em; text-align:justify;">
    Um die Komplexität der entwickelten Wissenbasis zu abstrahieren und die Nutzbarkeit für die Benutzer (z.B. Patienten und Therapeuten) zu erhöhen, haben wir eine Menge von Formularen in diese OntoWiki-Installation integriert.
    <br /><br />
    Zum Testen des aktuellen Standes unser Implementieriung melden Sie sich bitte mit folgenden Benutzerdaten an:

</p>
<p style="border: 1px dashed grey; background-color: #efefef; margin:1em; padding:1em ">
    Benutzer: guest <br>
    Passwort: guest123
</p>
