<div style="padding:1em;">
<img style="float:left; width: 8em; margin:1em;" src="/htdocs/dispedia/page/dispedia_logo.png" />

<h1>
    Dispedia - <span style="font-style:italic;">Demonstration</span>
</h1>

<p style="text-indent:1em; text-align:justify;">
    In order to abstract the complexity of the developed knowledge bases and to increase the usability for users (like patients and therapists) we integrated a set of forms 
    into this OntoWiki-installation. 
    <br><br>
    To test the existing state of our Implementation please log in with the following credentials:
    </p>
<p style="border: 1px dashed grey; background-color: #efefef; margin:1em; padding:1em ">
    User: guest <br>
    Password: guest123
</p>
