<div id="header">
    <div id="headerImage">
        <img src="<?php echo $this->baseUri ?>/img/eHealth_Services_2014.png" alt="ehealth Services 2014 Logo" />
    </div>
    <div id="headerText">
        <?php echo $this->literal(array('uri' => $this->wikiBaseUrl . 'Header', 'property' => 'http://ns.ontowiki.net/SysOnt/Site/headline', 'tag' => 'div', 'class' => 'headerTextHeadline')); ?>
    </div>
    <div class="clear"></div>
</div>