<img style="float:right; width: 8em; margin:1em;" src="../extensions/page/page/dispedia_logo.png" />

<h1>
Dispedia - <span style="font-style:italic;">Linked information systems for rare diseases.</span>
</h1>

<h2>Architectur - Description</h2>
<p style="text-indent:1em; text-align:justify; padding: 1em;">

<h2 style="border-bottom:1px solid lightgrey">Ontolgies and Concepts</h2>
<p style="text-align:center; width:100%">
<img align=center  style="margin:1em; width:50%" src="../extensions/page/page/schema.png" />
</p>


<h2 style="border-bottom:1px solid lightgrey">Interlinking with the Data Web</h2>
<p style="text-align:center; width:100%">
<img align=center  style="margin:1em; width:50%" src="../extensions/page/page/linking.png" />
</p>
