<div id="header">
    <div id="headerTitle">
        <div id="headerImage">
            <img src="<?php echo $this->baseUri ?>/img/ehealthservices2013_Logo_Bildmarke_transparent.png" alt="Dispedia logo" />
        </div>
        <?php echo $this->literal(array('uri' => 'http://www.ehealth-services-2013.de/Header', 'property' => 'http://ns.ontowiki.net/SysOnt/Site/title', 'tag' => 'div', 'class' => 'first')); ?>
        <?php echo $this->literal(array('uri' => 'http://www.ehealth-services-2013.de/Header', 'property' => 'http://ns.ontowiki.net/SysOnt/Site/titleline', 'tag' => 'div', 'class' => 'second', 'iprefix' => '<span>', 'isuffix' => '</span>')); ?>
    </div>
    <div id="headerText">
        <?php echo $this->literal(array('uri' => 'http://www.ehealth-services-2013.de/Header', 'property' => 'http://ns.ontowiki.net/SysOnt/Site/headline', 'tag' => 'div', 'class' => 'headerTextHeadline')); ?>
    </div>
    <div class="clear"></div>
</div>