<div id="dispedia-Cda2rdfModule-Content"> 
    <form action="/dispedia/cda2rdf" id="dispedia-Cda2rdfModule-form" name="dispedia-Cda2rdfModule-form" enctype="multipart/form-data" method="post">
        <fieldset>
            <label for="file-input"> Datei (max. 2 MB) </label>
            <input id="dispedia-Cda2rdfModule-file-input" type="file" name="xmlFileName" accept="application/xml">
        </fieldset>
    </form>
    <div id="dispedia-Cda2rdfModule-buttons">
        <a id="dispedia-Cda2rdfModule-addPatientFileButton" class="button"><?php echo $this->_translate->_('add'); ?></a>
        <a id="dispedia-Cda2rdfModule-resetButton" class="button reset"><?php echo $this->_translate->_('abort'); ?></a>
    </div>
</div>

