<?php 
/**
 * Template for index action
 * 
 * @category   OntoWiki
 * @package    OntoWiki_extensions_propalloc
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>  

<h1><?php echo $this->_translate->_('Create Proposal'); ?></h1>

<div><?php echo $this->_translate->_('indexDescriptionText'); ?></div>

<br/>
<form method="post" action="" id="propalloc">
	
    <table>
        <tr>
            <td style="width:15%">
                <strong><?php echo $this->_translate->_('ProposalName'); ?></strong>
            </td>
            <td>
                <input type="text" name="proposalName" style="width:400px;"/>
            </td>
        </tr>
        <tr>
            <td valign="top">
                <strong><?php echo $this->_translate->_('ProposalText'); ?></strong>
            </td>
            <td>
                <textarea style="width:400px; height:150px;" name="proposalText"></textarea>
            </td>
        </tr>
    </table>
    <hr>
    <br/>
    
    <!-- ########################################################### -->
    
    <table>
        <tr>
            <td style="width:15%">
                <strong><?php echo $this->_translate->_('ActionTitle'); ?></strong>
            </td>
            <td>
                <input type="text" name="actionTitle" style="width:250px;"/>
            </td>
        </tr>
        <tr>
            <td valign="top">
                <strong><?php echo $this->_translate->_('ActionText'); ?></strong>
            </td>
            <td>
                <textarea style="min-width:250px; width:250px; min-height:70px; height:70;" name="actionText"></textarea>
            </td>
        </tr>
    </table>
    
    
    <input type="hidden" name="actionUri" value=""/>
    
    <!-- ########################################################### -->
    
    <input type="hidden" name="do" value="save"/>

	<a id="addResource" class="button submit" onclick="document.forms['propalloc'].submit();"/>
		<?php echo $this->_translate->_('Save'); ?></a>
</form>
