<?php 
/**
 * Template for index action
 * 
 * @category   OntoWiki
 * @package    OntoWiki_extensions_propalloc
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>

<!-- important variables -->
<script type="text/javascript">       
    var url = '<?php echo $this->url; ?>';
</script>

<div class="proposalFirstline">
    <span><?php echo $this->_translate->_('Create Proposal'); ?></span>
</div>
<div class="proposalSecondline">
<span><?php echo $this->_translate->_('indexDescriptionText'); ?></span>
</div>
<form method="post" action="" id="propalloc">
    
    <div id="editProposal">
        <table>
            <tr>
                <td>
                    <strong><?php echo $this->_translate->_('label'); ?></strong>
                </td>
                <td>
                    <input type="hidden" name="currentProposal[uri]" value="<?php echo $this->currentProposal['uri']?>" />
                    <input type="hidden" name="currentProposal[hash]" value="<?php echo $this->currentProposal['hash']; ?>" />
                    <input type="text" name="currentProposal[label]" style="width:400px;" value="<?php echo (isset($this->currentProposal['label']) ? $this->currentProposal['label'] : ""); ?>" />
                </td>
                <td>
                    <a id="addActions" class="button" onclick="addEntity('Action', 'currentProposal[actions]', 'proposalActions');">
                        <?php echo $this->_translate->_('add action'); ?>
                    </a>
                </td>
            </tr>
        </table>
        <div id="proposalActions">
            <?php
                if (isset($this->actions))
                {
                    $this->actionOverClass = "currentProposal[actions]";
                    //Loop for proposal actions
                    foreach ($this->actions as $this->action) {
                        if (false !== array_search('action' . $this->action['hash'], $this->currentProposal['actions']))
                            echo $this->render('propalloc/action.phtml');
                    }
                }
            ?>
        </div>
    </div>
    
    <input type="hidden" name="currentProposal[status]" value="<?php echo $this->currentProposal['status']?>"/>
    <input type="hidden" name="currentProposalOldData" value="<?php echo urlencode(json_encode($this->currentProposal)); ?>"/>
    <input type="hidden" name="do" value="save"/>

    <a id="addResource" class="button submit" onclick="document.forms['propalloc'].submit();"/>
        <?php echo $this->_translate->_('Save'); ?>
    </a>
</form>
