<?php 
/**
 * Template for index action
 * 
 * @category   OntoWiki
 * @package    OntoWiki_extensions_propalloc
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>


<script src="http://sysinno.uni-leipzig.de/innotool/icf/scripz/prototype.js" type="text/javascript"></script>
<script src="http://sysinno.uni-leipzig.de/innotool/icf/scripz/scriptaculous.js" type="text/javascript"></script>
<script src="d3.v2.js" type="text/javascript"></script>
<script src="http://sysinno.uni-leipzig.de/innotool/icf/scripz/public/icfViewJSHelper.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="http://sysinno.uni-leipzig.de/innotool/icf/scripz/public/extern.css">
        
<div id="testDiv" class="patient-edit-main-div"></div>

<?php 
     $t = file_get_contents("http://sysinno.uni-leipzig.de/innotool/icf/external.php?patient=3&user=1");
?>

<script type="text/javascript">
/// patient / user
//test = new ajaxRequest(7,7);
//test.getFromExternal();
view = new icfViewHelper($("testDiv"));

var json = <?php echo $t ?>;


view.loopAndGetContent(json, 0);


</script>