<?php 
/**
 * Template for form action
 * 
 * @category   OntoWiki
 * @package    OntoWiki_extensions_formgenerator
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>
<script>
// http://flowplayer.org/tools/demos/scrollable/vertical.html
// execute your scripts when DOM is ready. this is a good habit
$(function() {		
		
	// initialize scrollable with mousewheel support
	$(".scrollable").scrollable({ vertical: true, mousewheel: true });	
	
});
</script>

<table style="width:100%">
    <tr>
        <td style="width:35%;" valign="top"></td>
        <td style="width:65%;" valign="top"></td>
    </tr>
    <tr>
        <!-- Proposals -->
        <td>
            <?php foreach ( $this->proposals as $proposal ) { ?>
                
                <br/>
                <div class="proposalItem">
                    <a href="<?php echo $this->url; ?>?proposal=<?php echo $proposal ['shortcut']; ?>">
                        <?php echo $proposal ['label']; ?></a>
                </div>
            
            <?php } ?>
        </td>
        
        <!-- ALSFRS topics and their options -->
        <td>
            <?php if ( '' != $this->currentProposal ) { ?>
                <div class="scrollable vertical">                
                    <div class="items">
                        <?php foreach ( $this->topics as $topic ) { ?>
                            
                            <div>
                                <div class="item">
                                    <!-- Topic label -->
                                    <h2><?php echo $topic ['label']; ?></h2>
                                    
                                    <!-- Options -->
                                    <ul>
                                    
                                    <?php foreach ( $topic ['options'] as $option ) { ?>
                                    
                                        <li><?php echo $option ['label']; ?></li>
                                    
                                    <?php } ?>
                                    
                                    </ul>
                                </div>
                            </div>
                        
                        <?php } ?>
                    </div>
                </div>        
            <?php } ?>
        </td>
    </tr>
</table>
