<?php 
/**
 * Template for form action
 * 
 * @category   OntoWiki
 * @package    OntoWiki_extensions_formgenerator
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>
<table style="width:100%">
    <tr>
        <td style="width:50%;" valign="top"></td>
        <td style="width:50%;" valign="top"></td>
    </tr>
    <tr>
        <td></td>
        
        <!-- ALSFRS options -->
        <td></td>
    </tr>
</table>
