<?php 
/**
 * Template for information action
 * 
 * @category   OntoWiki
 * @package    OntoWiki_extensions_propalloc
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>
<?php $information = $this->information ?>
<?php $informationName = "information" . $information['hash']; ?>
<input type="hidden" name="<?php echo $informationName; ?>OldData" value="<?php echo urlencode(json_encode($information)); ?>"/>
<table class="<?php echo $informationName; ?> information">
    <tr class="tablehead">
        <th>
            <span class="headline"><?php echo $this->_translate->_('information'); ?></span>
        </th>
        <th>
            <a id="removeInformation" class="button" onclick="removeEntity('<?php echo $informationName; ?>');">
                <?php echo $this->_translate->_('remove information'); ?>
            </a>
        </th>
    </tr>
    <tr>
        <td>
            <strong><?php echo $this->_translate->_('label'); ?></strong>
        </td>
        <td>
            <input type="hidden" name="<?php echo $informationName; ?>[status]" value="<?php echo $this->information['status']?>"/>
            <?php if(isset($this->informationOverClass)) { ?>
                <input type="hidden" name="<?php echo $this->informationOverClass ?>[]" value="<?php echo $informationName; ?>" />
            <?php } ?>
            <input type="hidden" name="<?php echo $informationName; ?>[uri]" value="<?php echo $information['uri']; ?>" />
            <input type="hidden" name="<?php echo $informationName; ?>[hash]" value="<?php echo $information['hash']; ?>" />
            <input type="text" name="<?php echo $informationName; ?>[label]" style="width:400px;" value="<?php echo (isset($information['label']) ? $information['label'] : ""); ?>" />
        </td>
        <td>
            <strong><?php echo $this->_translate->_('informationType'); ?></strong>
        </td>
        <td>
            <strong><?php echo $this->_translate->_('therapistType'); ?></strong>
        </td>
    </tr>
    <tr class="<?php echo "information" . $information['hash']; ?>">
        <td>
            <!-- TODO: labels aus ontologie holen und mit übergeben -->
            <strong><?php echo $this->_translate->_('content'); ?></strong>
        </td>
        <td>
            <textarea style="width:400px; height:150px;" name="<?php echo $informationName; ?>[content]"><?php echo (isset($information['content']) ? $information['content'] : ""); ?></textarea>
        </td>
        <td>
            <?php foreach ($this->informationClasses as $informationClassUri => $informationClassLabel) { ?>
                <input type="checkbox" name="<?php echo $informationName; ?>[informationClasses][]" style="width:400px;" value="<?php echo $informationClassUri; ?>" <?php echo (isset($information['informationClass'][$informationClassUri]) ? "checked=\"checked\"" : ""); ?> /><?php echo $informationClassLabel; ?><br />
            <?php } ?>
        </td>
        <td>
            <?php foreach ($this->therapistClasses as $therapistClassUri => $therapistClassLabel) { ?>
                <input type="checkbox" name="<?php echo $informationName; ?>[therapistClasses][]" style="width:400px;" value="<?php echo $therapistClassUri; ?>" <?php echo (isset($information['usefulFor'][$therapistClassUri]) ? "checked=\"checked\"" : ""); ?> /><?php echo $therapistClassLabel; ?><br />
            <?php } ?>
        </td>
    </tr>
    </table>