<?php 
/**
 * Template for supporter class overview action
 * 
 * @category   OntoWiki
 * @package    OntoWiki_extensions_propalloc
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>

<!-- set the title of the action -->
<?php $this->placeholder('main.window.title')->set($this->_translate->_('supporterClassesAdministration')); ?>

<h1><?php echo $this->_translate->_('supporterClassesAdministration'); ?></h1>

<table style="width:100%">
    <?php if ( 0 < count ( $this->supporterClasses ) ) { ?>
        <tr>
            <td style="width:35%;" valign="top"></td>
            <td style="width:65%;" valign="top"></td>
    </tr>
        <tr>
            <!-- SupporterClasses -->
            <td>
                <?php foreach ( $this->supporterClasses as $supporterClass ) { ?>
                    <div class="$supporterClassItem">
                        <a href="<?php echo $this->url; ?>supporterclass?supporterClassUri=<?php echo urlencode($supporterClass['uri']); ?>">
                            <img src="<?php echo $this->imagesUrl; ?>edit.png" align="absmiddle"/>
                        </a>&nbsp;
                        <a href="<?php echo $this->url; ?>supporterclassremove?supporterClassUri=<?php echo urlencode($supporterClass['uri']); ?>">
                            <img src="<?php echo $this->imagesUrl; ?>cross.png" align="absmiddle"/>
                        </a>&nbsp;
                        <?php echo $supporterClass ['label']; ?>
                    </div>
                <?php } ?>
            </td>
        </tr>
    <?php } ?>
</table>