<?php 
/**
 * Template for index action
 * 
 * @category   OntoWiki
 * @package    OntoWiki_extensions_propalloc
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>

<div class="proposalFirstline">
    <span><?php echo $this->_translate->_('createTherapistClass'); ?></span>
</div>
<div class="proposalSecondline">
    <span><?php echo $this->_translate->_('therapistDescriptionText'); ?></span>
</div>
<form method="post" action="" id="therapist">
    <table>
        <tr>
            <td>
                <strong><?php echo $this->_translate->_('labelde'); ?></strong>
            </td>
            <td>
                <input type="hidden" name="currentTherapistClass[uri]" value="<?php echo (isset($this->currentTherapistClass['uri']) ? $this->currentTherapistClass['uri'] : ""); ?>" />
                <input type="text" name="currentTherapistClass[labelde]" style="width:400px;" value="<?php echo (isset($this->currentTherapistClass['labelde']) ? $this->currentTherapistClass['labelde'] : ""); ?>" />
            </td>
        </tr>
        <tr>
            <td>
                <strong><?php echo $this->_translate->_('labelen'); ?></strong>
            </td>
            <td>
                <input type="text" name="currentTherapistClass[labelen]" style="width:400px;" value="<?php echo (isset($this->currentTherapistClass['labelen']) ? $this->currentTherapistClass['labelen'] : ""); ?>" />
            </td>
        </tr>
    </table>
    <input type="hidden" name="currentProposal[status]" value="<?php echo $this->currentTherapistClass['status']?>"/>
    <input type="hidden" name="currentProposalOldData" value="<?php echo urlencode(json_encode($this->currentTherapistClass)); ?>"/>
    <input type="hidden" name="do" value="save"/>

    <a id="addResource" class="button submit" onclick="document.forms['therapist'].submit();"/>
        <?php echo $this->_translate->_('Save'); ?>
    </a>
</form>