<div class="program">
    <?php
        echo $this->literal(array('property' => 'http://ns.ontowiki.net/SysOnt/Site/time', 'tag' => 'div', 'class' => 'time'));
        
        echo $this->literal(array('property' => 'http://www.w3.org/2000/01/rdf-schema#label', 'tag' => 'div', 'class' => 'name'));
        
        echo $this->literal(array('property' => 'http://ns.ontowiki.net/SysOnt/Site/referent', 'tag' => 'div', 'class' => 'referent', 'iprefix' => 'Referent: '));
        
        echo $this->literal(array('tag' => 'div', 'class' => 'programContent'));
        
    ?>
</div>