<div class="program">
    <?php
        echo $this->literal(array('property' => 'http://ns.ontowiki.net/SysOnt/Site/time', 'tag' => 'div', 'class' => 'time'));
    ?>
    <div class="clear"></div>
    <?php
        echo $this->literal(array('property' => 'http://www.w3.org/2000/01/rdf-schema#label', 'tag' => 'div', 'class' => 'name'));
    ?>
    <div class="lectures">
        <?php
            // prepare lecture rows
            $queryForLectures = '
            PREFIX foaf: <http://xmlns.com/foaf/0.1/>
            SELECT DISTINCT ?resourceUri
            WHERE {
                ?resourceUri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ns.ontowiki.net/SysOnt/Site/Referente> .
                <' . $this->resourceUri . '> ?number ?resourceUri .
                ?resourceUri <http://www.w3.org/2000/01/rdf-schema#label> ?label .
            }
            ORDER BY ASC(?number)';
            $lectures = $this->querylist($queryForLectures, 'ehealthservices2013/items/lecture.phtml');
            echo $lectures;
        ?>
    </div>
        
</div>