<?php 
/**
 * Template for main menu
 * 
 * @category   OntoWiki
 * @package    OntoWiki_extensions_formgenerator
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>

<!-- important variables -->
<script type="text/javascript">       
    var url = '<?php echo $this->url; ?>';
</script>

<!-- User is not logged in -->
<?php if ( false == $this->loggedIn ) { ?>

<div>
    <img src="<?php echo $this->imagesUrl; ?>dispedia_logo.png" border="0" align="absmiddle"/>
    <a href="">
        <?php echo $this->_translate->_('Overview'); ?></a>
</div>

<!-- User is logged in -->
<?php } else { ?>

<!-- patient select box -->
<div id="divSelectPatient">
    <form method="post" action="#">
        <select name="selectPatient" id="selectPatient">
            <option value=""><?php echo $this->_translate->_('noPatientSelected'); ?></option>
            <?php foreach ($this->patients as $patientUri => $patientLabel) { ?>
                <option value="<?php echo urldecode($patientUri); ?>"<?php echo ($this->currentPatientUri == $patientUri ? 'selected="selected"' : ""); ?>><?php echo $patientLabel; ?></option>
            <?php }; ?>
        </select>
    </form>
</div>

<script>
    $("#selectPatient").trigger('change');
    $("#selectPatient").change(function () {
        var uri = $("#selectPatient option:selected").val();
        if ('' == uri)
        {
            uri = "http://ns.ontowiki.net/SysOnt/Model";
        }
        $.ajax({
            async:true,
            dataType: "html",
            type: "POST",
            url: url + "resource/properties/?m=http%3A%2F%2Fpatients.dispedia.de%2F&r=" + uri,
            // complete, no errors
            success: function ( res ) 
            {
                location.reload();
            },
            
            error: function (jqXHR, textStatus, errorThrown)
            {
                console.log (jqXHR);
                console.log (textStatus);
                console.log (errorThrown);
            }
        });
    })
</script>

<div>
    <img src="<?php echo $this->imagesUrl; ?>dispedia_logo.png" border="0" align="absmiddle"/>
    &nbsp;
    <a id="ahome" href="<?php echo $this->url; ?>">
        <?php echo $this->_translate->_('Home'); ?></a>
</div>

<div>
    <img src="<?php echo $this->imagesUrl; ?>user.png" border="0" align="absmiddle"/>
    &nbsp;
    <a id="apatient" href="javascript: void(0)">
        <?php echo $this->_translate->_('Patient view'); ?></a>
</div>

<div>
    <img src="<?php echo $this->imagesUrl; ?>user_doctor.png" border="0" align="absmiddle"/>
    &nbsp;
    <a id="adoctor" href="javascript: void(0)">
        <?php echo $this->_translate->_('Doctor view'); ?></a>
</div>

<div>
    <img src="<?php echo $this->imagesUrl; ?>ow_logo.png" border="0" align="absmiddle" width="16"/>
    &nbsp;
    <a id="aadmin" href="javascript: void(0)">
        <?php echo $this->_translate->_('Admin view'); ?></a>
</div>

<script type="text/javascript">

    function setMenu(menuName)
    {
        $.ajax({
            async:true,
            dataType: "html",
            type: "POST",
            data: {menuName : menuName},
            url: url + "formsmainmenu/setmenu",
            
            error: function (jqXHR, textStatus, errorThrown)
            {
                console.log (jqXHR);
                console.log (textStatus);
                console.log (errorThrown);
            }
        });
    }
    
    $(document).ready(function() {
        <?php if ( 'patient' != $this->showMenu ) echo "$('#divpatient').addClass('hidden');" ?>
        <?php if ( 'doctor' != $this->showMenu ) echo "$('#divdoctor').addClass('hidden');" ?>
        <?php if ( 'admin' != $this->showMenu ) echo "$('#divadmin').addClass('hidden');" ?>
    });
    
    $('#ahome').click(function() {
        setMenu('');
    });
    $('#apatient').click(function() {
        setMenu('patient');
        if ($('#divpatient').hasClass('hidden'))
        {
            $('#divpatient').removeClass('hidden');
            $('#divdoctor').addClass('hidden');
            $('#divadmin').addClass('hidden');
        }
        else {
            $('#divpatient').addClass('hidden');
        }
    });
    $('#adoctor').click(function() {
        setMenu('doctor');
        if ($('#divdoctor').hasClass('hidden'))
        {
            $('#divpatient').addClass('hidden');
            $('#divdoctor').removeClass('hidden');
            $('#divadmin').addClass('hidden');
        }
        else {
            $('#divdoctor').addClass('hidden');
        }
    });
    $('#aadmin').click(function() {
        setMenu('admin');
        if ($('#divadmin').hasClass('hidden'))
        {
            $('#divpatient').addClass("hidden");
            $('#divdoctor').addClass("hidden");
            $('#divadmin').removeClass("hidden");
        }
        else {
            $('#divadmin').addClass('hidden');
        }
    });
</script>

<!-- ###################################################### -->
<div id="divpatient">
    <br />
    <hr />
    <!-- Submenu -->
    
    <div style="font-weight:bold; font-size:16px;">
        <?php echo $this->_translate->_('Patient view'); ?>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>user_edit.png" border="0" align="absmiddle"/>    
        &nbsp;&nbsp;
        <a href="<?php echo $this->url ?>formgenerator/form?file=patientEdit">
            <?php echo $this->_translate->_('Edit patient information'); ?></a>
    </div>
    
    <br/>
    <div style="font-weight:bold; font-size:13px;">
        <?php echo $this->_translate->_('Edit family status'); ?>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>family.png" border="0" align="absmiddle"/>    
        &nbsp;&nbsp;
        <a href="<?php echo $this->url ?>formgenerator/form?file=familystatus">
            <?php echo $this->_translate->_('Family status'); ?></a>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>relations.png" border="0" align="absmiddle"/>    
        &nbsp;
        <a href="<?php echo $this->url ?>formgenerator/form?file=livingRelations">
            <?php echo $this->_translate->_('Living relations'); ?></a> /
        <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="<?php echo $this->url ?>formgenerator/form?file=children">
            <?php echo $this->_translate->_('Children'); ?></a> /
        <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="<?php echo $this->url ?>formgenerator/form?file=silbings">
            <?php echo $this->_translate->_('Silbings'); ?></a>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>spouse.png" border="0" align="absmiddle"/>    
        &nbsp;
        <a href="<?php echo $this->url ?>formgenerator/form?file=lifePartnerSpouse">
            <?php echo $this->_translate->_('Life partner / spouse'); ?></a>
    </div>
    
    <br/>
    <div style="font-weight:bold; font-size:13px;">
        <?php echo $this->_translate->_('Edit housing situation'); ?>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>house.png" border="0" align="absmiddle"/>    
        &nbsp;&nbsp;&nbsp;
        <a href="<?php echo $this->url ?>formgenerator/newform?file=address">
            <?php echo $this->_translate->_('Add address'); ?></a>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>user_house.png" border="0" align="absmiddle"/>    
        &nbsp;
        <a href="<?php echo $this->url ?>formgenerator/form?file=setAddress">
            <?php echo $this->_translate->_('Set Address'); ?></a>
    </div>

    <br/>
    <div style="font-weight:bold; font-size:13px;">
        <?php echo $this->_translate->_('Edit professional situation'); ?>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>wrench.png" border="0" align="absmiddle"/>    
        &nbsp;&nbsp;&nbsp;
        <a href="<?php echo $this->url ?>formgenerator/form?file=job">
            <?php echo $this->_translate->_('Job'); ?></a>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>relations.png" border="0" align="absmiddle"/>    
        
        <a href="<?php echo $this->url ?>formgenerator/form?file=socialSituation">
            <?php echo $this->_translate->_('Social situation'); ?></a>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>sport_basketball.png" border="0" align="absmiddle"/>    
        &nbsp;&nbsp;&nbsp;
        <a href="<?php echo $this->url ?>formgenerator/form?file=hobbies">
            <?php echo $this->_translate->_('Hobbies'); ?></a>
    </div>

    <br/>
    <div style="font-weight:bold;font-size:13px;">
        <?php echo $this->_translate->_('Proposals'); ?>
    </div>
    <div style="font-size:12px;">
        <img src="<?php echo $this->imagesUrl; ?>poll_create.png" border="0" align="absmiddle"/>
        &nbsp;&nbsp;
        <a href="<?php echo $this->url ?>patapro/patient">
            <?php echo $this->_translate->_('Decisions'); ?></a>
    </div>
</div>

<!-- ###################################################### -->
<div id="divdoctor">
    <br />
    <hr />
    <div style="font-weight:bold; font-size:16px;">
        <?php echo $this->_translate->_('Doctor view'); ?>
    </div>
    <br/>
    
    <div style="font-weight:bold;font-size:14px;">
        <?php echo $this->_translate->_('Proposal and proposal allocations'); ?>
    </div>
    <div style="font-size:12px;">
        <img src="<?php echo $this->imagesUrl; ?>application_side_tree.png" border="0" align="absmiddle"/>
        &nbsp;
        <a href="<?php echo $this->url ?>list?init&m=http%3A%2F%2Fals.dispedia.de%2F&&instancesconfig=%7B%22filter%22%3A%5B%7B%22rdfsclass%22%3A%22http%3A%5C%2F%5C%2Fwww.dispedia.de%5C%2Fo%5C%2FProposal%22%2C%22mode%22%3A%22rdfsclass%22%7D%5D%7D">
            <?php echo $this->_translate->_('Proposal overview'); ?></a>
    </div>
    
    <div style="font-size:12px;">
        <img src="<?php echo $this->imagesUrl; ?>pill.png" border="0" align="absmiddle"/>
        &nbsp;
        <a href="<?php echo $this->url ?>formgenerator/newform?file=proposal">
            <?php echo $this->_translate->_('Create proposal'); ?></a>
    </div>
    
    <div style="font-size:12px;">
        <img src="<?php echo $this->imagesUrl; ?>poll_create.png" border="0" align="absmiddle"/>
        &nbsp;
        <a href="<?php echo $this->url ?>propalloc/alloc">
            <?php echo $this->_translate->_('proposalAllocation'); ?></a>
    </div>
    <div style="font-size:12px;">
        <img src="<?php echo $this->imagesUrl; ?>poll_create.png" border="0" align="absmiddle"/>
        &nbsp;
        <a href="<?php echo $this->url ?>patapro">
            <?php echo $this->_translate->_('Patient proposal allocation'); ?></a>
    </div>
    <br/>
    
    <div style="font-weight:bold;font-size:14px;">
        <?php echo $this->_translate->_('medical condition'); ?>
    </div>
    
    <div style="font-weight:bold;font-size:12px;">
        <?php echo $this->_translate->_('By classification'); ?>
        <br/>
        <li>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="<?php echo $this->url ?>formgenerator/form?file=alsfrs">
                <?php echo $this->_translate->_('ALSFRS'); ?></a>
        </li>
        <li>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="<?php echo $this->url ?>propalloc/icf">
            <?php echo $this->_translate->_('ICF'); ?></a>
             / 
            <a href="http://sysinno.uni-leipzig.de/innotool/ICF/index.php" target="_blank">
            <?php echo $this->_translate->_('icfTool'); ?></a></a>
        </li>
    </div>
    
    
    <br/>
    <div style="font-weight:bold;font-size:12px;">
        <?php echo $this->_translate->_('By free text'); ?>
    </div>
    
    <div>
        <img src="<?php echo $this->imagesUrl; ?>aim.png" border="0" align="absmiddle"/>    
        &nbsp;
        <a href="<?php echo $this->url ?>formgenerator/form?file=movement">
            <?php echo $this->_translate->_('Movement'); ?></a>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>cart.png" border="0" align="absmiddle"/>    
        &nbsp;
        <a href="<?php echo $this->url ?>formgenerator/form?file=diet">
            <?php echo $this->_translate->_('Diet'); ?></a>
    </div>
</div>

<!-- ###################################################### -->
<div id="divadmin">
    <br />
    <hr />
    <div style="font-weight:bold; font-size:16px;">
        <?php echo $this->_translate->_('Admin view'); ?>
    </div>
    <br />
    
    <div style="font-weight:bold; font-size:14px;">
        <?php echo $this->_translate->_('user'); ?>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>user_add.png" border="0" align="absmiddle"/>    
        &nbsp;
        <a href="<?php echo $this->url ?>list?init&m=http%3A%2F%2Fpatients.dispedia.de%2F&instancesconfig=%7B%22filter%22%3A%5B%7B%22rdfsclass%22%3A%22http%3A%5C%2F%5C%2Fwww.dispedia.de%5C%2Fo%5C%2FPerson%22%2C%22mode%22%3A%22rdfsclass%22%7D%5D%7D">
            <?php echo $this->_translate->_('persons'); ?></a>
        <a href="<?php echo $this->url ?>formgenerator/newform?file=person">
            <img src="<?php echo $this->imagesUrl; ?>add.png" height="16px" border="0" align="absmiddle"/>
        </a>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>user_add.png" border="0" align="absmiddle"/>    
        &nbsp;
        <a href="<?php echo $this->url ?>list?init&m=http%3A%2F%2Fpatients.dispedia.de%2F&instancesconfig=%7B%22filter%22%3A%5B%7B%22rdfsclass%22%3A%22http%3A%5C%2F%5C%2Fwww.dispedia.de%5C%2Fo%5C%2FPatient%22%2C%22mode%22%3A%22rdfsclass%22%7D%5D%7D">
            <?php echo $this->_translate->_('patients'); ?></a>
        <a href="<?php echo $this->url ?>formgenerator/newform?file=patient">
            <img src="<?php echo $this->imagesUrl; ?>add.png" height="16px" border="0" align="absmiddle"/>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>user_add.png" border="0" align="absmiddle"/>    
        &nbsp;
        <a href="<?php echo $this->url ?>list?init&m=http%3A%2F%2Fhc.dispedia.de%2F&instancesconfig=%7B%22filter%22%3A%5B%7B%22rdfsclass%22%3A%22http%3A%5C%2F%5C%2Fwww.serviceOntology.org%5C%2FOrganization%22%2C%22mode%22%3A%22rdfsclass%22%7D%5D%7D">
            <?php echo $this->_translate->_('organizations'); ?></a>
        <a href="<?php echo $this->url ?>formgenerator/newform?file=organization">
            <img src="<?php echo $this->imagesUrl; ?>add.png" height="16px" border="0" align="absmiddle"/>
        </a>
    </div>
    <br />
    <div style="font-weight:bold; font-size:14px;">
        <?php echo $this->_translate->_('services'); ?>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>user_add.png" border="0" align="absmiddle"/>    
        &nbsp;
        <a href="<?php echo $this->url ?>list?init&m=http%3A%2F%2Fhc.dispedia.de%2F&instancesconfig=%7B%22filter%22%3A%5B%7B%22rdfsclass%22%3A%22http%3A%5C%2F%5C%2Fwww.serviceOntology.org%5C%2FService%22%2C%22mode%22%3A%22rdfsclass%22%7D%5D%7D">
            <?php echo $this->_translate->_('services'); ?></a>
        <a href="<?php echo $this->url ?>formgenerator/newform?file=service">
            <img src="<?php echo $this->imagesUrl; ?>add.png" height="16px" border="0" align="absmiddle"/>
        </a>
    </div>
    <br />
    <!--<div style="font-size:12px;">
        <img src="<?php echo $this->imagesUrl; ?>user_doctor.png" border="0" align="absmiddle"/>
        &nbsp;
        <a href="<?php echo $this->url ?>propalloc/supporterclassoverview">
            <?php echo $this->_translate->_('supporterClassOverview'); ?></a>
    </div>
    <div style="font-size:12px;">
        <img src="<?php echo $this->imagesUrl; ?>user_doctor.png" border="0" align="absmiddle"/>
        &nbsp;
        <a href="<?php echo $this->url ?>propalloc/supporterclass">
            <?php echo $this->_translate->_('newSupporterClass'); ?></a>
    </div>
    <br />-->
    <div style="font-weight:bold; font-size:14px;">
        <?php echo $this->_translate->_('categories'); ?>
    </div>
    <div style="font-size:12px;">
        <img src="<?php echo $this->imagesUrl; ?>user_doctor.png" border="0" align="absmiddle"/>
        &nbsp;
        <a href="<?php echo $this->url ?>formgenerator/newform?file=organizationCategory">
            <?php echo $this->_translate->_('orgnizationCategory'); ?>
        </a>
    </div>
    <div style="font-size:12px;">
        <img src="<?php echo $this->imagesUrl; ?>user_doctor.png" border="0" align="absmiddle"/>
        &nbsp;
        <a href="<?php echo $this->url ?>formgenerator/newform?file=serviceCategory">
            <?php echo $this->_translate->_('serviceCategory'); ?>
        </a>
    </div>
    <br />
    <div style="font-weight:bold; font-size:14px;">
        <?php echo $this->_translate->_('ontologies'); ?>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>database_add.png" border="0" align="absmiddle"/>
        &nbsp; 
        <a href="<?php echo $this->url ?>patapro/store">
            <?php echo $this->_translate->_('ontologieEdit'); ?></a>
    </div>
    <br />
    <div style="font-weight:bold; font-size:14px;">
        <?php echo $this->_translate->_('OntoWiki'); ?>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>user_add.png" border="0" align="absmiddle"/>
        &nbsp; 
        <a href="<?php echo $this->applicationUrl ?>register">
            <?php echo $this->_translate->_('Register a new user'); ?></a>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>database_add.png" border="0" align="absmiddle"/>
        &nbsp;
        <a href="<?php echo $this->url ?>model/create">
            <?php echo $this->_translate->_('Add a new knowledge base'); ?></a>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>wrench.png" border="0" align="absmiddle"/>
        &nbsp;
        <a href="<?php echo $this->applicationUrl ?>preferences">
            <?php echo $this->_translate->_('Preferences'); ?></a>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>package.png" border="0" align="absmiddle"/>
        &nbsp;
        <a href="<?php echo $this->url ?>exconf/list">
            <?php echo $this->_translate->_('Extensions'); ?></a>
    </div>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>database_gear.png" border="0" align="absmiddle"/>
        &nbsp;
        <a href="<?php echo $this->url ?>queries/editor">
            <?php echo $this->_translate->_('QueryEditor'); ?></a>
    </div>
    
    <br/>
    <div>
        <img src="<?php echo $this->imagesUrl; ?>door_in.png" border="0" align="absmiddle"/>
        &nbsp;
        <a href="<?php echo $this->applicationUrl ?>logout">
            <?php echo $this->_translate->_('Logout'); ?></a>
    </div>
</div>

<?php } ?>
