<!-- User is not logged in -->
<?php if ( false == $this->loggedIn ) { ?>

<div>
    <img src="<?php echo $this->imagesUrl; ?>dispedia_logo.png" border="0" align="absmiddle"/>
    <a href="">
        <?php echo $this->_translate->_('Overview'); ?></a>
</div>

<!-- User is logged in -->
<?php } else { ?>

<div>
    <img src="<?php echo $this->imagesUrl; ?>dispedia_logo.png" border="0" align="absmiddle"/>
    &nbsp;
    <a href="<?php echo $this->url; ?>resource/instances/?m=http%3A%2F%2Fals.dispedia.info%2F">
        <?php echo $this->_translate->_('Overview'); ?></a>
</div>

<div>
    <img src="<?php echo $this->imagesUrl; ?>user.png" border="0" align="absmiddle"/>
    &nbsp;
    <a href="<?php echo $this->url; ?>?showMenu=patient">
        <?php echo $this->_translate->_('Patient view'); ?></a>
</div>

<div>
    <img src="<?php echo $this->imagesUrl; ?>user_doctor.png" border="0" align="absmiddle"/>
    &nbsp;
    <a href="<?php echo $this->url; ?>?showMenu=doctor">
        <?php echo $this->_translate->_('Doctor view'); ?></a>
</div>

<div>
    <img src="<?php echo $this->imagesUrl; ?>ow_logo.png" border="0" align="absmiddle" width="16"/>
    &nbsp;
    <a href="<?php echo $this->url; ?>?showMenu=ontowiki">
        <?php echo $this->_translate->_('System'); ?>
    </a>
</div>

<?php if ( 'patient' == $this->showMenu ) { ?>

<br/>

<!-- Submenu -->

<div style="font-weight:bold; font-size:16px;">
    <?php echo $this->_translate->_('Patient view'); ?>
</div>
<div>
    <img src="<?php echo $this->imagesUrl; ?>user_add.png" border="0" align="absmiddle"/>    
    &nbsp;
    <a href="<?php echo $this->url ?>formgenerator/form?file=patient">
        <?php echo $this->_translate->_('Add a new patient'); ?></a>
</div>
<div>
    <img src="<?php echo $this->imagesUrl; ?>user_edit.png" border="0" align="absmiddle"/>    
    &nbsp;
    <a href="<?php echo $this->url ?>formgenerator/form?file=patientEdit">
        <?php echo $this->_translate->_('Edit patient information'); ?></a>
</div>

<br/>
<div style="font-weight:bold; font-size:13px;">
    <?php echo $this->_translate->_('Edit family status'); ?>
</div>
<div>
    <img src="<?php echo $this->imagesUrl; ?>family.png" border="0" align="absmiddle"/>    
    &nbsp;
    <a href="<?php echo $this->url ?>formgenerator/form?file=familystatus">
        <?php echo $this->_translate->_('Family status'); ?></a>
</div>
<div>
    <img src="<?php echo $this->imagesUrl; ?>relations.png" border="0" align="absmiddle"/>    
    &nbsp;
    <a href="<?php echo $this->url ?>formgenerator/form?file=livingRelations">
        <?php echo $this->_translate->_('Living relations'); ?></a> / 
    <a href="<?php echo $this->url ?>formgenerator/form?file=children">
        <?php echo $this->_translate->_('Children'); ?></a> / 
    <a href="<?php echo $this->url ?>formgenerator/form?file=silbings">
        <?php echo $this->_translate->_('Silbings'); ?></a>
</div>
<div>
    <img src="<?php echo $this->imagesUrl; ?>spouse.png" border="0" align="absmiddle"/>    
    &nbsp;
    <a href="<?php echo $this->url ?>formgenerator/form?file=lifePartnerSpouse">
        <?php echo $this->_translate->_('Life partner / spouse'); ?></a>
</div>
<div>
    <img src="<?php echo $this->imagesUrl; ?>tux.png" border="0" align="absmiddle"/>    
    &nbsp;
    <a href="<?php echo $this->url ?>formgenerator/form?file=pet">
        <?php echo $this->_translate->_('Add pet'); ?></a> /
    <a href="<?php echo $this->url ?>formgenerator/form?file=setPets">
        <?php echo $this->_translate->_('Set Pets'); ?></a>
</div>

<br/>
<div style="font-weight:bold; font-size:13px;">
    <?php echo $this->_translate->_('Edit housing situation'); ?>
</div>
<div>
    <img src="<?php echo $this->imagesUrl; ?>house.png" border="0" align="absmiddle"/>    
    &nbsp;
    <a href="<?php echo $this->url ?>formgenerator/form?file=address">
        <?php echo $this->_translate->_('Add address'); ?></a>
</div>
<div>
    <img src="<?php echo $this->imagesUrl; ?>user_house.png" border="0" align="absmiddle"/>    
    &nbsp;
    <a href="<?php echo $this->url ?>formgenerator/form?file=setAddress">
        <?php echo $this->_translate->_('Set Address'); ?></a>
</div>

<br/>
<div style="font-weight:bold; font-size:13px;">
    <?php echo $this->_translate->_('Edit medical condition'); ?>
</div>
<div>
    <img src="<?php echo $this->imagesUrl; ?>aim.png" border="0" align="absmiddle"/>    
    &nbsp;
    <a href="<?php echo $this->url ?>formgenerator/form?file=movement">
        <?php echo $this->_translate->_('Movement'); ?></a>
</div>
<div>
    <img src="<?php echo $this->imagesUrl; ?>cart.png" border="0" align="absmiddle"/>    
    &nbsp;
    <a href="<?php echo $this->url ?>formgenerator/form?file=diet">
        <?php echo $this->_translate->_('Diet'); ?></a>
</div>

<br/>
<div style="font-weight:bold; font-size:13px;">
    <?php echo $this->_translate->_('Edit professional situation'); ?>
</div>
<div>
    <img src="<?php echo $this->imagesUrl; ?>wrench.png" border="0" align="absmiddle"/>    
    &nbsp;
    <a href="<?php echo $this->url ?>formgenerator/form?file=job">
        <?php echo $this->_translate->_('Job'); ?></a>
</div>
<div>
    <img src="<?php echo $this->imagesUrl; ?>relations.png" border="0" align="absmiddle"/>    
    &nbsp;
    <a href="<?php echo $this->url ?>formgenerator/form?file=socialSituation">
        <?php echo $this->_translate->_('Social situation'); ?></a>
</div>
<div>
    <img src="<?php echo $this->imagesUrl; ?>sport_basketball.png" border="0" align="absmiddle"/>    
    &nbsp;
    <a href="<?php echo $this->url ?>formgenerator/form?file=hobbies">
        <?php echo $this->_translate->_('Hobbies'); ?></a>
</div>


<?php } elseif ( 'ontowiki' == $this->showMenu ) { ?>

<br/>

<!-- Submenu -->

<div style="font-weight:bold; font-size:16px;">
    <?php echo $this->_translate->_('OntoWiki'); ?>
</div>
<div>
    <img src="<?php echo $this->imagesUrl; ?>user_add.png" border="0" align="absmiddle"/>    
    <a href="<?php echo $this->applicationUrl ?>register">
        <?php echo $this->_translate->_('Register a new user'); ?></a>
</div>
<div>
    <img src="<?php echo $this->imagesUrl; ?>database_add.png" border="0" align="absmiddle"/>    
    <a href="<?php echo $this->url ?>model/create">
        <?php echo $this->_translate->_('Add a new knowledge base'); ?></a>
</div>
<div>
    <img src="<?php echo $this->imagesUrl; ?>wrench.png" border="0" align="absmiddle"/>        
    <a href="<?php echo $this->applicationUrl ?>preferences">
        <?php echo $this->_translate->_('Preferences'); ?></a>
</div>
<div>
    <img src="<?php echo $this->imagesUrl; ?>package.png" border="0" align="absmiddle"/>        
    <a href="<?php echo $this->url ?>exconf/list">
        <?php echo $this->_translate->_('Extensions'); ?></a>
</div>

<br/>
<div>
    <img src="<?php echo $this->imagesUrl; ?>door_in.png" border="0" align="absmiddle"/>        
    <a href="<?php echo $this->applicationUrl ?>logout">
        <?php echo $this->_translate->_('Logout'); ?></a>
</div>

<?php } ?>

<?php } ?>
