<?php 
$style = '' == $this->showMenu
         ? 'font-weight:bold; font-size:16px;'
         : '' ; 
?>
    
    
    <div style="<?php echo $style; ?>">
        <a href="<?php echo $this->actionUrl ?>?showMenu=patient">
            <?php echo $this->_translate->_('Patient view'); ?>
        </a>
    </div>

    <div style="<?php echo $style; ?>">
        <a href="<?php echo $this->actionUrl ?>?showMenu=doctor">
            <?php echo $this->_translate->_('Doctor view'); ?>
        </a>
    </div>

    <div style="<?php echo $style; ?>">
        <a href="<?php echo $this->actionUrl; ?>?showMenu=patient">
            <?php echo $this->_translate->_('Therapist'); ?>
        </a>
    </div>
    
<?php if ( 'patient' == $this->showMenu ) { ?>

    <hr/>
    <br/>

<!-- Submenu -->

    <div style="font-weight:bold; font-size:16px;">
        <?php echo $this->_translate->_('Patient view'); ?>
    </div>

    <div>
        <a href="<?php echo $this->actionUrl ?>?showMenu=patient">
            <?php echo $this->_translate->_('Master data'); ?>
        </a>
    </div>

    <div>
        <a href="<?php echo $this->actionUrl ?>?showMenu=patient">
            <?php echo $this->_translate->_('Family status'); ?>
        </a>
    </div>

    <div>
        <a href="<?php echo $this->actionUrl ?>?showMenu=patient">
            <?php echo $this->_translate->_('supervised by'); ?>
        </a>
    </div>
    
    <br/>

<?php } ?>
